modified the time color change to be specific to the id of the box. debugging the on click function to figure out why TypeError: (scheduleSave + saving).val is not a function